# Generated by Django 3.0.5 on 2023-03-10 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_type', models.CharField(choices=[('Katrina', 'Katrina'), ('Blockout', 'Blockout'), ('Sheer', 'Sheer'), ('None', 'None')], max_length=250, null=True)),
                ('payment', models.CharField(choices=[('GCASH', 'GCASH'), ('CASH ON DELIVERY', 'CASH ON DELIVERY'), ('LBC', 'LBC'), ('OTHERS', 'OTHERS')], max_length=250, null=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('color', models.CharField(max_length=250, null=True)),
                ('product_tag', models.SmallIntegerField(choices=[(1, 'Blockout'), (2, '5-in-1 Katrina'), (3, '3-in-1 Katrina'), (4, 'Tieback Holder')])),
                ('set_tag', models.CharField(choices=[('5-in-1', '5-in-1'), ('3-in-1', '3-in-1'), ('Single', 'Single'), ('None', 'None')], max_length=250, null=True)),
                ('month_of_purhase', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('qty', models.PositiveIntegerField(null=True)),
                ('count', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, null=True)),
                ('profile_pic', models.ImageField(default='fchub/static/profile_pic/customer_profile_pic/akbay.png', null=True, upload_to='fchub/static/profile_pic/customer_profile_pic')),
                ('gender', models.SmallIntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'other')])),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('region', models.CharField(max_length=250, null=True)),
                ('province', models.CharField(max_length=250, null=True)),
                ('barangay', models.CharField(max_length=250, null=True)),
                ('city', models.CharField(max_length=250, null=True)),
                ('zipcode', models.PositiveIntegerField()),
                ('street', models.CharField(max_length=250, null=True)),
                ('detailed_address', models.CharField(max_length=250, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('qty', models.CharField(max_length=250)),
                ('unit', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('product_img', models.ImageField(blank=True, null=True, upload_to='fchub/static/product_img/product_pic')),
                ('price', models.PositiveIntegerField()),
                ('fabric_type', models.CharField(max_length=250)),
                ('set_type', models.CharField(max_length=250)),
                ('qty', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('product_tag', models.SmallIntegerField(choices=[(1, 'Blockout'), (2, '5-in-1 Katrina'), (3, '3-in-1 Katrina'), (4, 'Tieback Holder')])),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psgcCode', models.IntegerField(blank=True, null=True, verbose_name='psgcCode')),
                ('regDesc', models.CharField(blank=True, max_length=255, null=True, verbose_name='regDesc')),
                ('regCode', models.IntegerField(blank=True, null=True, verbose_name='regCode')),
            ],
        ),
        migrations.CreateModel(
            name='province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psgcCode', models.IntegerField(blank=True, null=True, verbose_name='psgcCode')),
                ('provDesc', models.CharField(blank=True, max_length=255, null=True, verbose_name='provDesc')),
                ('provCode', models.IntegerField(blank=True, null=True, verbose_name='provCode')),
                ('regCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fchub.region')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(max_length=250, null=True)),
                ('province', models.CharField(max_length=250, null=True)),
                ('barangay', models.CharField(max_length=250, null=True)),
                ('city', models.CharField(max_length=250, null=True)),
                ('zipcode', models.PositiveIntegerField(null=True)),
                ('street', models.CharField(max_length=250, null=True)),
                ('detailed_address', models.CharField(max_length=250, null=True)),
                ('mobile', models.CharField(max_length=250, null=True)),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=50, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fchub.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fchub.Product')),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psgcCode', models.IntegerField(blank=True, null=True, verbose_name='psgcCode')),
                ('citymunDesc', models.CharField(blank=True, max_length=255, null=True, verbose_name='citymunDesc')),
                ('regDesc', models.IntegerField(blank=True, null=True, verbose_name='regDesc')),
                ('citymunCode', models.IntegerField(blank=True, null=True, verbose_name='citymunCode')),
                ('provCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fchub.province')),
            ],
        ),
        migrations.CreateModel(
            name='barangay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brgyCode', models.IntegerField(blank=True, null=True, verbose_name='brgyCod')),
                ('brgyDesc', models.CharField(blank=True, max_length=255, null=True, verbose_name='brgyDesc')),
                ('regCode', models.IntegerField(blank=True, null=True, verbose_name='regCode')),
                ('provCode', models.IntegerField(blank=True, null=True, verbose_name='provCode')),
                ('citymunCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fchub.city')),
            ],
        ),
    ]
