# Generated by Django 3.0.5 on 2023-03-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='barangay',
            new_name='barangay_text',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='city',
            new_name='city_text',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='province',
            new_name='province_text',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='region',
            new_name='region_text',
        ),
    ]
